version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Japan
  open-pull-requests-limit: 10
