version: 2
jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - run:
          command: |
            apt update
            apt install -y openjdk-11-jre-headless unzip

      - run:
          command: |
            wget -O vnu.zip https://github.com/validator/validator/releases/download/18.11.5/vnu.jar_18.11.5.zip
            unzip vnu.zip

      - restore_cache:
          key: requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.test.txt" }}

      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt -r requirements.test.txt

      - save_cache:
          key: requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.test.txt" }}
          paths:
            - "venv"

      - run:
          command: |
            source venv/bin/activate
            flake8 advent gen_tweet.py

      - run:
          command: |
            source venv/bin/activate
            mypy --strict advent

      - run:
          command: |
            source venv/bin/activate
            python -m advent

      - run:
          command: java -jar dist/vnu.jar --verbose output/index.html
