name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Vnu
        run: |
          wget -O vnu.zip https://github.com/validator/validator/releases/download/20.6.30/vnu.jar_20.6.30.zip
          unzip vnu.zip

      - name: Cache Python Deps
        id: cache
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-${{ hashFiles('require.txt') }}-${{ hashFiles('require.test.txt') }}

      - name: Install Python Deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt -r requirements.test.txt

      - run: |
          source venv/bin/activate
          flake8 advent tests
          
      - run: |
          source venv/bin/activate
          mypy --strict advent
          
      - run: |
          source venv/bin/activate
          pytest -vv
          
      - run: |
          source venv/bin/activate
          python -m advent
          
      - run: |
          java -jar dist/vnu.jar --verbose output/index.html
